### ISSUE TITLE
Alzheimers failed drugs listed as PhaseIII

### ISSUE THREAD

**Issue by ckongEbi** [opentargets/data_release#18]
@deniseOme 

ADUCANUMAB BAPINEUZUMAB GANTENERUMAB SOLANEZUMAB

these drugs failed, should be reflected in the next chembl release. 

https://www.targetvalidation.org/evidence/ENSG00000142192/EFO_0000249?view=sec:known_drugs

**Comment by ckongEbi** [comment]
@deniseOme update from ChEMBL

Regarding the status of the trials on these drugs, our latest update of the clinicaltrials.gov data was done in November last year. Because we are so close to the ChEMBL release now we are not planning to do another update before that, but I checked the 29 trials that are shown in the Open Targets platform and the status hasn’t changed for them, except for 4 trials:

NCT01127633 changed from Active, not recruiting to Terminated
NCT01900665 changed from Active, not recruiting to Terminated
NCT02051608 changed from Active, not recruiting to Completed
NCT02760602 changed from Recruiting to Active, not recruiting

(There is no ‘Failed’ status in clinicaltrials.gov, and if the drug fails it’s difficult to obtain this information from here. So we normally include the trial status: https://clinicaltrials.gov/ct2/about-studies/glossary#recruitment-status)

**Comment by deniseOme** [comment]
@ckongEbi, just showed this to @iandunham. We will need to talk to ChEMBL about this.

**Comment by deniseOme** [comment]
Hi @ckongEbi, let's have a look at NCT01900665 (https://clinicaltrials.gov/ct2/show/NCT01900665). The drug did not meet the study's primary endpoint. These are some of the press information:

http://www.nature.com/news/failed-alzheimer-s-trial-does-not-kill-leading-theory-of-disease-1.21045

https://investor.lilly.com/releasedetail.cfm?ReleaseID=1000871

You have noted that NCT01900665 changed from Active, not recruiting to Terminated.

Will this impact on the scoring for data type Drugs in the next releases?

**Comment by ckongEbi** [comment]
@deniseOme currently no, we only score base on the phase information. Will be good to have that information included in the scoring we do have them in the JSON.
