### ISSUE TITLE
missing RNA experiment to support association

### ISSUE THREAD

**Issue by nikiforosk** [opentargets/data_release#22]
CST1 - asthma
https://www.targetvalidation.org/evidence/ENSG00000170373/EFO_0000270?view=sec:literature

This association is currently supported by Text Mining evidence only. However, looking at the Atlas we noticed this experiment which also seems to support this association:
https://www.ebi.ac.uk/gxa/experiments/E-GEOD-19187?geneQuery=ENSG00000170373&queryFactorValues=g1_g4&specific=false

We noticed this by searching the Atlas for asthma ("CST1" and "uncontrolled asthma" appear in the 3rd result):
https://www.ebi.ac.uk/gxa/query?geneQuery=%5B%5D&organism=homo%20sapiens&conditionQuery=%5B%7B%22value%22%3A%22asthma%22%7D%5D&ds=%7B%22kingdom%22%3A%5B%22animals%22%5D%7D#differential

**Comment by nikiforosk** [comment]
Is it possible to compare queries like this:
https://www.ebi.ac.uk/gxa/query?geneQuery=%5B%5D&organism=homo%20sapiens&conditionQuery=%5B%7B%22value%22%3A%22asthma%22%7D%5D&ds=%7B%22kingdom%22%3A%5B%22animals%22%5D%7D#differential

with the data that Atlas sends us to identify such gaps?

**Comment by ckongEbi** [comment]
in this case it is the disease i.e. uncontrolled asthma that does not have an ontology, Laura will look at curating them and submit them for EFO
