### ISSUE TITLE
Unexpected disease_id format 

### ISSUE THREAD

**Issue by ckongEbi** [opentargets/data_release#47]
In the `17.12` Genomics England JSON, there are 251 evidence that has unexpected disease_id format. 

e.g
"validation_errors": "u'http://purl.obolibrary.org/obo/NCBITaxon_265669'
"validation_errors": "u'http://purl.obolibrary.org/obo/NCBITaxon_36470'
"validation_errors": "u'http://purl.obolibrary.org/obo/CHEBI_31746'
"validation_errors": "u'http://purl.obolibrary.org/obo/TO_0000387'

We need to re-visit the disease mapping process and fix them

**Comment by ckongEbi** [comment]
@gkos-bio upon fixing the OLS API , we manage to reduce the number of evidence that has unexpected disease_id. 

There is still one evidence with issue 
 "validation_errors": ("u'http://purl.obolibrary.org/obo/UBERON_0012316') 
"url": "https://panelapp.genomicsengland.co.uk/panels/57acb8268f620364dc61afd3"}]}
"panel_name": "Clefting"

**Comment by ckongEbi** [comment]
Reported to SPOT team, the OLS API should return 400 error code for a bad request. When we provide a wrong parameter `eact` instead of `exact`

https://github.com/EBISPOT/OLS/issues/183#issuecomment-352787281

**Comment by elipapa** [comment]
Issue moved to [opentargets/evidence_datasource_parsers #2](https://github.com/opentargets/evidence_datasource_parsers/issues/2) via [**ZenHub**](https://www.zenhub.com/)
