### ISSUE TITLE
Unexpected disease_id format

### ISSUE THREAD

**Issue by ckongEbi** [opentargets/data_release#48]
In the 17.12 Phewas JSON, there are 791 evidence that has unexpected disease_id format.

e.g
"validation_errors": "u'http://purl.obolibrary.org/obo/NCBITaxon_623'
"validation_errors": "u'http://purl.obolibrary.org/obo/NCBITaxon_1392'
"validation_errors": "u'http://purl.obolibrary.org/obo/NCBITaxon_29459'

We need to re-visit the disease mapping process and fix them

**Comment by ckongEbi** [comment]
@elipapa identified the possible bug and will re-visit/re-factor the phewas code to eradicate this issue.

**Comment by elipapa** [comment]
Issue moved to [opentargets/evidence_datasource_parsers #1](https://github.com/opentargets/evidence_datasource_parsers/issues/1) via [**ZenHub**](https://www.zenhub.com/)
