### ISSUE TITLE
Datasources licensing

### ISSUE THREAD

**Issue by ckongEbi** [opentargets/data_release#50]
To revisit existing datasource license and capture the licensing information in our help pages.

**Comment by ElaineMcA** [comment]
Support docs/ FAQ update.

**Comment by ckongEbi** [comment]
Something along these lines in the help pages

![screen shot 2018-07-25 at 14 43 48](https://user-images.githubusercontent.com/6169985/43204560-26d9cd58-9019-11e8-93c2-7d739ef305f7.png)

**Comment by ElaineMcA** [comment]
Issue moved to [opentargets/platform #43](https://github.com/opentargets/platform/issues/43) via [**ZenHub**](https://www.zenhub.com/)
