### ISSUE TITLE
New drug for Huntington Disease

### ISSUE THREAD

**Issue by ckongEbi** [opentargets/data_release#51]
There is a new drug ONIS-HTT(Rx) in initial trial phase for Huntington Disease. 

[http://www.aljazeera.com/news/2017/12/drug-offers-hope-treating-huntington-disease-171211145705425.html](url)

This is the clinical trial:

[https://clinicaltrials.gov/ct2/show/NCT02519036](url)

We need to ensure it comes through our ChEMBL data feed. 

cc: @deniseOme, @iandunham

**Comment by deniseOme** [comment]
Thanks @ckongEbi for logging this after my email. As I said, the drug is supposed to target the HTT gene. 

Shouldn't this be in ChEMBL already as the start date of clinical trial is 2015?

**Comment by ckongEbi** [comment]
@deniseOme, they might have the trials in their database but as this drug/MOA is not in ChEMBL currently, the link to create the JSON is missing.

**Comment by ckongEbi** [comment]
ChEMBL will update once they have more news. No expected date provided for now.

**Comment by ckongEbi** [comment]
should feed through the data feed once ChEMBL_24 released in Feb. But might not get into OT 18.02 release though.

**Comment by ckongEbi** [comment]
The drug will get into ChEMBL but not OT for the reason below. 
@deniseOme 
On 13/04/2018 09:28, Maria Paula Magarinos wrote:
> Hi ChuangKee,
>
> The drug is not in ChEMBL yet. We are working in a process to load compounds from Clinical Trials into ChEMBL when necessary. However in this particular case, because the target of the drug is not a protein but RNA, the target won’t have a Uniprot ID and therefore it won’t be included in the JSON fie.
> Cheers,
Ok , we will take note, thanks!
>
>
> Paula
>

**Comment by iandunham** [comment]
Our model doesn't specify the modality that is used to modulate the target. So we treat all modalities (through protein or RNA, or anything else) as mediated through the conceptual entity of 'target'. The target has a uniprot id in this case (for the HTT protein) so they could use that, or if they don't wnat to do that they can use the Ensembl gene id

**Comment by ckongEbi** [comment]
@iandunham right, will revisit when they get the compound into ChEMBL

**Comment by iandunham** [comment]
There might be other drugs that they are not annotating with a target for this reason - would be worht reopening the discussion with them soon.

**Comment by ckongEbi** [comment]
@MichaelaEBI @ElaineMcA @iandunham post-discussion with ChEMBL. They are still working on adding this new drug to ChEMBL , while we agree to try to use the ENSG id for the RNA target

**Comment by ElaineMcA** [comment]
Issue moved to [opentargets/platform #44](https://github.com/opentargets/platform/issues/44) via [**ZenHub**](https://www.zenhub.com/)
