### ISSUE TITLE
Streamline disease mapping in evidence parsers + refactor evidence parsers

### ISSUE THREAD

**Issue by ckongEbi** [opentargets/data_release#53]
### **Background**
Currently, our evidence parsers https://github.com/opentargets/evidence_datasource_parsers/tree/master/modules each implement within their module, own disease mapping process. This is not ideal for maintaining mapping consistencies. 

### **Aims**
Some high level objectives to achieve:

1. Review the disease mapping logic, including addition of new terms to EFO, automate that if it is not the case currently. 
2. Abstract the disease mapping logic from various evidence parsers, build an independent disease mapping module/package. Adapt various evidence parsers to use this.
3. The way the evidence parsers is written currently indirectly do the schema validation, which is done in a later stage of the evidence submission process. Removing that will increase efficiency of the parsers code.

### **Task** [to be expanded]

- [ ] @ckongEbi to organise meeting in Jan 18 to consolidate understanding on the issue.

**Comment by ckongEbi** [comment]
Copying in suggestions/discussions from slack here for reference:

@gkos-bio 
Hi there. 
Have you started to talk about the PheWAS evidence generation improvement? 
There is a few things to consider more generally on the evidence_datasource_parsers that I would like to point out. 
One aspect is the HP terms that are not currently in EFO. 
If we can spit out a list of HP terms that are not in EFO (and are not diseases),  it will be easier to integrate them in the data pipeline.
For GenomicsEngland for instance, there is also a list of such terms
Ideally, I would like to collect them in one QC step of the pipeline for review before the validation.

@elipapa
i am 100% behind this. 
Can I suggest one step further? What if we replace the (now) manual addition to terms to our EFO for each release with an automated process?
Something along the lines of: 
if the data maps to EFO use it;
elif it has a xref to EFO use that; 
elif _it maps to another major ontology keep that mapping and expand our ontology_
else log/spit out the lack of mapping, so we can map the data point manually in a second pass.
what do you think?

**@ gkos-bio**
Your suggestions are good. 
Did you know that in the original pipeline I would have checked for HP terms anyway?
Did you know that there a module sitting in the data pipeline to take a set of HP terms, create a slim of HP and plug it to our EFO based ontology?
This needs a bit of refactoring with your suggestions but basically it's there!

cc @iandunham @MichaelaEBI

**Comment by elipapa** [comment]
moved to https://github.com/opentargets/epics/issues/95
