### ISSUE TITLE
European Clinical Trials Database

### ISSUE THREAD

**Issue by elipapa** [opentargets/data_release#54]
@deniseOme commented on [Fri Mar 10 2017](https://github.com/opentargets/platform_issues/issues/25)

Follow on a question at omics data integration: is it worth curating drug information from the European Clinical Trials Database? What are the differences when compared to clinicaltrials.gov or daily med?

https://eudract.ema.europa.eu/

---

@iandunham commented on [Fri Mar 10 2017](https://github.com/opentargets/platform_issues/issues/25#issuecomment-285663609)

One to ask Chembl about. 

---

@ckongEbi commented on [Tue Apr 25 2017](https://github.com/opentargets/platform_issues/issues/25#issuecomment-296962806)

@elipapa can you move this to data-providers repo https://github.com/opentargets/data-providers-docs/issues, i take it up with ChEMBL

**Comment by ckongEbi** [comment]
Further discussion planned with ChEMBL around the new datasource

**Comment by elipapa** [comment]
opentrials.net is another useful website to bring to the discussion

________________________________

**Comment by ckongEbi** [comment]
@iandunham should we request chEMBL to assess the coverage of the WHO ICTRP & Opentrials.net VS CT.gov ?

**Comment by iandunham** [comment]
Paula's comment suggests they already looked at this - 20% new. We could ask her to assess how much new is coming from clinicaltrials.gov each month and whether a better hit rate would come from the other sources. We also would need to assess whether she will be able to continue curating new data from clincialtrials.gov

**Comment by ckongEbi** [comment]
So far they didn't has the chance to looked at the 20% new from ICTRP, from the conversation, they currently have resources to support the ongoing submission but not focus on curation of new trials/resources etc.

**Comment by ckongEbi** [comment]
This should be looked at by ChEMBL in a larger scope collaboration effort with them
