### ISSUE TITLE
Text-Mining Better handling of acronyms (Targets & Disease)

### ISSUE THREAD

**Issue by ckongEbi** [opentargets/data_release#60]
- [ ] Explore options to compare Open Targets Library/[LINK](http://blog.opentargets.org/link/) with Europe PMC text mining (obtain data from OT Library via API etc.)

Hi CK,

 Can you ask the EMPC to fix this in their next release of the data.

Gene UCN3 has a synonym SPC and Open targets states that there are over 300 references to UCN3 and respiratory disease but the issue is that there is a lung cancer cell line called SPC-A1 and this is what is picked up by the text mining.

It’s somewhat misleading if users are checking for disease associations of targets (by headline data/numbers only).

SPC also stands for small primary cancers (SPC).I have seen other examples for other genes too.
Is there a  way of refining the text mining e.g.  to include SPC but NOT SPC-A1?

More generally, because EMPC is only mining proteins and diseases, they miss the all point about other entities (in this case SPC-A1 refers to a cell line).

That’s what Andrea tried to solve with Spacy.

If they add a dictionary of cell lines a better handling of acronyms, this would probably solve some of our problems.

Best wishes,
Gautier

cc @gkos-bio @iandunham

**Comment by ckongEbi** [comment]
EPMC will add this to their blacklist when generating evidence. We can extend that from the compiled TP data from integration day currently working on by @MichaelaEBI. 

A longer term acronym & cell line strategy with EPMC to be discussed.

**Comment by ckongEbi** [comment]
TP data from integration day here https://docs.google.com/spreadsheets/d/1RiYCYdD-XHPbEszQKsZvKkC2Y2utAKNj9oC_YgpWEeU/edit#gid=0

**Comment by ckongEbi** [comment]
Acronym filtering to be done on OT side.

**Comment by ElaineMcA** [comment]
Issue moved to [opentargets/platform #48](https://github.com/opentargets/platform/issues/48) via [**ZenHub**](https://www.zenhub.com/)
