### ISSUE TITLE
Additional gene-drug interaction data from DGIdb

### ISSUE THREAD

**Issue by ckongEbi** [opentargets/data_release#64]
Talk to chembl about coverage of the gene-drug interaction data - 
e.g. BRAF has 100 entries in dgidb (http://dgidb.org/api/v2/interactions.json?genes=BRAF)
vs 13 entris given to us from chebml (http://www.targetvalidation.org/target/ENSG00000157764).

Are these all synonyms ? or is there additional data : Can we include the DGIdb data pnto the drug entity page via a drug search e.g. http://dgidb.org/api/v2/interactions.json?drugs=dabrafenib or into the target profile page as in the target search http://dgidb.org/api/v2/interactions.json?genes=BRAF How much new will we get vs Chembl data feed?

**Comment by ckongEbi** [comment]
Comparing drug-gene interactions for BRAF between:

DGIdb vs OT : 
http://dgidb.org/api/v2/interactions.json?genes=ENSG00000157764
https://api.opentargets.io/v3/platform/private/target/ENSG00000157764

These is a list of drug interactions found in DGIdb but NOT in OT platform: 

CHEMBL526479
NIVOLUMAB
OMIPALISIB
UPROSERTIB
CHEMBL525191
CEDIRANIB
GEDATOLISIB
TEMSIROLIMUS
CETUXIMAB
TRAMETINIB
Refametinib
PANITUMUMAB
PANOBINOSTAT
FLUOROURACIL
SELUMETINIB
E-6201
CRIZOTINIB
SAR-260301
CHEMBL1231206
OXALIPLATIN
INK-128
BINIMETINIB
PEMBROLIZUMAB
TAK-733
NAVITOCLAX
PD-0325901
GEFITINIB
PILARALISIB (CHEMBL3218575)
BUPARLISIB
SARACATINIB
ZSTK-474
CHEMBL2204502

**Comment by ElaineMcA** [comment]
Issue moved to [opentargets/platform #51](https://github.com/opentargets/platform/issues/51) via [**ZenHub**](https://www.zenhub.com/)
