### ISSUE TITLE
Scope out and define role of small molecules in Open Targets

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/data_release#76]
The plan is to expand Drug to an entity in the Open Targets platform.
- [x] Meet with ChEMBL to discuss our issues & questions
- [x] What do we gain by making Drug an entity?
- [x] Definition of drug entity fields and connections
- [x] Define user perspective, ie., what additional information will they get
- [x] Definition of terms with ChEMBL (drugs with and without targets, chemical probes etc.)
- [x] Identify data that needs to be pulled in
- [ ] Compare PubChem and DrugBank with ChEMBL. Has ChEMBL analysed differential coverage of the databases?
- [ ] Look at licensing for data sources
- [ ] Define steps for implementation

Also see [here](https://github.com/opentargets/data_pipeline/issues/233).

**Comment by MichaelaEBI** [comment]
**Update on Drug Entity April 19, 2018:**

- Anna presented at the OT lab meeting yesterday, she will be in touch shortly to arrange a meeting so that we can work through our [drug entity-related document](https://docs.google.com/document/d/1OybXEkESjKp46bprAJBy2xXGONKnXGxM5F1NsvlYVC8/edit#).

**Comment by ElaineMcA** [comment]
Issue moved to [opentargets/platform #10](https://github.com/opentargets/platform/issues/10) via [**ZenHub**](https://www.zenhub.com/)
