### ISSUE TITLE
Reactome data file has wrong name in 18.06 release

### ISSUE THREAD

**Issue by pieterlukasse** [opentargets/data_release#87]
The file `reactome-01-06-2018.gz` should be named `reactome-01-06-2018.json.gz` in https://console.cloud.google.com/storage/browser/ot-releases/18.06/ . Currently the wrong name results in errors when running the `--val` step. Error:
```
mrtarget.modules.EvidenceValidation - ERROR - failed to parse and get tokens from filename ...
```

**Comment by pieterlukasse** [comment]
Notify: @ckongEbi @mkarmona

**Comment by ckongEbi** [comment]
thanks ! now fixed
